version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  assignees:
  - mydea
  ignore:
  - dependency-name: ember-source
    versions:
    - 3.24.0
    - 3.24.1
  - dependency-name: ember-data
    versions:
    - 3.23.0
    - 3.24.0
  - dependency-name: ini
    versions:
    - 1.3.7
